### ISSUE TITLE
undefined columns selected

### ISSUE THREAD

**Issue by YangChaoCN** [tapj/biotyper#1]
Hi, Dr Julien Tap,

I'm learning your BiotypeR.

when I tried k=2 in BCA analysis, these's an error like this: 
Error in `[.data.frame`(biotyper.obj$BET$ls, , yax) :   undefined columns selected

However, I can finish PCoA analysis. Does this mean that BCA can't deal with data when k<=2 ? why?

Yangchao

**Comment by tapj** [comment]
Dear Yangchao, 

You can still do a BCA with k=2 but you will obtain only one component which maximize the separation between your 2 clusters. As consequence, with a k=2 BCA you can not do a scatter 2D plot. With k=2 I would advise you to make a boxplot instead and check contributors with a barplot for example.


For any additionnal information about BCA I would advise you to read this R tutorial:

http://pbil.univ-lyon1.fr/R/pdf/course4.pdf

++
Ju.

**Comment by YangChaoCN** [comment]
thank you for your help, I'm trying to understand this.

another question, In the tutorial a graph is shown with the driver genera for each cluster projected onto the plots, but how to find the driver genera? I am quite new to R, could you give me some help?

Yangchao

**Comment by tapj** [comment]
see #3
