### ISSUE TITLE
Calculation of driver-taxa 

### ISSUE THREAD

**Issue by xmarti6** [tapj/biotyper#3]
Hi,
We are trying with to identify the driver-taxa of each cluster with the table produced by bca() analysis: obs.bet$tab. From there we have a score for each taxa in each cluster. To our first understanding the taxa playing  a major role in the cluster are those with highest absolute values (those further apart from the 0, either positive or negative values). But according to the results seems like the right values should be only those scores with highest positive values (not negatives). Can you confirm/give us five cents about this? 
Many thanks
Xavi

**Comment by tapj** [comment]
Hi,

Actually the any cluster is characterized by negative and positive driver associated, like you said. However, the way we named enterotypes was based only on positive association.

For instance, *Prevotella* enterotype is not *Prevotella* **associated** enterotype but *Prevotella* **enriched** enterotype.

Again, if you give a chance to look at the dirrichlet multinomial R package, it will give you a more elegant  solution imho to assign driver to enterotypes. 

*(Spoiler: the original method included in BiotypeR and the dirrichlet one gave in most of the case the same drivers for the same microbiota clusters)*

HTH,

Julien
